### ISSUE TITLE
How to set ${KICAD_USER_LIBRARY}?

### ISSUE THREAD

**Issue by sebastianbeyer** [holmesrichards/aoKicad#1]
Hey, I am happily using your library, but I noticed that the 3d models reference `${KICAD_USER_LIBRARY}` which is not set in my kicad. Is this a standard variable? Was it somehow lost during my upgrade to kicad 6.0? Can I just enter it as a new variable?

**Comment by holmesrichards** [comment]
Right, I should put that in the docs. No, KICAD_USER_LIBRARY isn't a standard variable, you can define it in KiCad however you want.

**Comment by sebastianbeyer** [comment]
Perfect! Thank you! :)
