### ISSUE TITLE
LM13700 pins mixed up

### ISSUE THREAD

**Issue by sebastianbeyer** [holmesrichards/aoKicad#2]
Hey, I think the pins of the inverting and non inverting inputs were mixed up during your last commit, could you double check?

![Screenshot from 2022-01-06 15-18-27](https://user-images.githubusercontent.com/7209020/148396847-78a7d0c9-f0da-4320-8624-f8d14d6ead6d.png)

![Screenshot from 2022-01-06 15-19-10](https://user-images.githubusercontent.com/7209020/148397125-964968b1-7198-4836-ae15-dbd1b084a86d.png)

**Comment by holmesrichards** [comment]
I did double check it. And got it wrong.
