### ISSUE TITLE
Jack and rotary switch footprints flag errors in KiCad 6

### ISSUE THREAD

**Issue by Sonosus** [holmesrichards/aoKicad#3]
With the new, more aggressive, DRC checking in KiCad v6, the rotary switch and jack footprints (and possibly more?) flag a 'Silkscreen clipped by solder mask' error.
![image](https://user-images.githubusercontent.com/67963676/151716528-580ced11-f170-40f8-97c5-fb0c86a66846.png)
![image](https://user-images.githubusercontent.com/67963676/151716550-e70f1d4d-7b06-4384-8a6d-ca9f244cbe48.png)

**Comment by holmesrichards** [comment]
You can turn off the silkscreen warnings in the board setup. So far I've been turning it off until I'm about ready to generate the Gerbers, then turn it on and see which ones I want to fix.

**Comment by holmesrichards** [comment]
OK, I do see this with the rotary switch, will fix. I do NOT see it with the jacks. Can you post a screenshot?
